@startuml

skinparam componentStyle uml2
skinparam component {
    backgroundColor<<JavaScript Library>> MistyRose
    backgroundcolor<<Java Library>> LightSkyBlue
}
skinparam linetype ortho


title Component diagram

rectangle "Admin App" as admin {
        [Admin App Home] <<Angular>> as ah
        [Frontend Core] <<Angular>> as fc
        [Frontend GUI] <<Angular / Angular Material>> as fg
        ah - fc
        ah -down- fg
        fc -up- fg
}


rectangle "Territorial App" as territ {
        [Territorial App Home] <<Angular>> as ah1
        [Frontend Core] <<Angular>> as fc1
        [Frontend GUI] <<Angular / Angular Material>> as fg1
        [OpenLayers4] <<JavaScript Library>> as ol1
        [Proj4js] <<JavaScript Library>> as p4js1
        component "Plugin Demo" <<Angular>> as pd
    
        
        fg1 -down- ol1
        fg1 -down- p4js1
        fg1 - fc1
        ah1 - fc1
        ah1 - fg1
        ah1 -down- pd
        
        pd - fg1
        pd - fc1
}

    
rectangle "Server" as server <<Server Spring5>> {
        component "Backend Core" <<Java - Spring 5>> as pcs #FEFECE {
            [REST Controller] as rest
            [Model] as model
        }
        interface "**REST API**" as api

}

[External WMS] as wms #MediumAquaMarine
ol1 -down- wms


database "Database (Back-Office)" as db{
}


:User:
:Administrator:

User -down- ah1 : <<Internet>>
Administrator -down- ah : <<Internet>>
fc -down-( api
fc1 -down-( api
api -down- rest
rest -down- model
model -down- "<<Spring JPA - Hibernate>>" db


@enduml
