@startuml
skinparam style strictuml
hide methods
hide members
class UserConfiguration [[java:org.sitmun.plugin.core.domain.UserConfiguration]] {
	-long id
	+long getId()
	+void setId(long id)
	+User getUser()
	+void setUser(User user)
	+Territory getTerritory()
	+void setTerritory(Territory territory)
	+Role getRole()
	+void setRole(Role role)
}
class User [[java:es.aragon.agoab.domain.User]] {
}
UserConfiguration --> "1" User : user
class Territory [[java:org.sitmun.plugin.core.domain.Territory]] {
}
UserConfiguration --> "1" Territory : territory
class Role [[java:org.sitmun.plugin.core.domain.Role]] {
}
UserConfiguration --> "1" Role : role
class TerritoryType [[java:org.sitmun.plugin.core.domain.TerritoryType]] {
	-long id
	-String name
	+long getId()
	+void setId(long id)
	+String getName()
	+void setName(String name)
}
class CartographyGroup [[java:org.sitmun.plugin.core.domain.CartographyGroup]] {
	-long id
	-String name
	-String type
	+long getId()
	+void setId(long id)
	+String getName()
	+void setName(String name)
	+String getType()
	+void setType(String type)
	+Set<Cartography> getMembers()
	+void setMembers(Set<Cartography> members)
	+Set<Role> getRoles()
	+void setRoles(Set<Role> roles)
}
class Cartography [[java:org.sitmun.plugin.core.domain.Cartography]] {
}
CartographyGroup --> "*" Cartography : members
class Role [[java:org.sitmun.plugin.core.domain.Role]] {
}
CartographyGroup --> "*" Role : roles
class Service [[java:org.sitmun.plugin.core.domain.Service]] {
	-long id
	-String name
	-String url
	-String projections
	-String legend
	-String infoUrl
	-Date createdDate
	+long getId()
	+void setId(long id)
	+String getName()
	+void setName(String name)
	+String getUrl()
	+void setUrl(String url)
	+String getProjections()
	+void setProjections(String projections)
	+String getLegend()
	+void setLegend(String legend)
	+String getInfoUrl()
	+void setInfoUrl(String infoUrl)
	+Date getCreatedDate()
	+void setCreatedDate(Date createdDate)
	+Set<Cartography> getLayers()
	+void setLayers(Set<Cartography> layers)
	+Connection getConnection()
	+void setConnection(Connection connection)
}
class Cartography [[java:org.sitmun.plugin.core.domain.Cartography]] {
}
Service --> "*" Cartography : layers
class Connection [[java:org.sitmun.plugin.core.domain.Connection]] {
}
Service --> "1" Connection : connection
class Background [[java:org.sitmun.plugin.core.domain.Background]] {
	-long id
	-String name
	-String description
	-Boolean active
	-Date createdDate
	+long getId()
	+void setId(long id)
	+String getName()
	+void setName(String name)
	+String getDescription()
	+void setDescription(String description)
	+Boolean getActive()
	+void setActive(Boolean active)
	+Date getCreatedDate()
	+void setCreatedDate(Date createdDate)
	+CartographyGroup getCartographyGroup()
	+void setCartographyGroup(CartographyGroup cartographyGroup)
}
class CartographyGroup [[java:org.sitmun.plugin.core.domain.CartographyGroup]] {
}
Background --> "1" CartographyGroup : cartographyGroup
class Application [[java:org.sitmun.plugin.core.domain.Application]] {
	-long id
	-String name
	-String type
	-String title
	-String theme
	-Date createdDate
	-String scales
	-String projections
	-Boolean treeAutoRefresh
	+Set<Tree> getArboles()
	+long getId()
	+void setId(long id)
	+String getName()
	+void setName(String name)
	+String getType()
	+void setType(String type)
	+String getTitle()
	+void setTitle(String title)
	+String getTheme()
	+void setTheme(String theme)
	+Date getCreatedDate()
	+void setCreatedDate(Date createdDate)
	+Set<Role> getAvailableRoles()
	+void setAvailableRoles(Set<Role> availableRoles)
	+Set<ApplicationParameter> getParameters()
	+void setParameters(Set<ApplicationParameter> parameters)
	+Set<Tree> getTrees()
	+void setTrees(Set<Tree> trees)
	+String getScales()
	+void setScales(String scales)
	+String getProjections()
	+void setProjections(String projections)
	+Boolean getTreeAutoRefresh()
	+void setTreeAutoRefresh(Boolean treeAutoRefresh)
	+Set<ApplicationBackground> getBackgrounds()
	+void setBackgrounds(Set<ApplicationBackground> backgrounds)
	+CartographyGroup getSituationMap()
	+void setSituationMap(CartographyGroup situationMap)
}
class Role [[java:org.sitmun.plugin.core.domain.Role]] {
}
Application -up-> "*" Role : availableRoles
class ApplicationParameter [[java:org.sitmun.plugin.core.domain.ApplicationParameter]] {
}
Application --> "*" ApplicationParameter : parameters
class Tree [[java:org.sitmun.plugin.core.domain.Tree]] {
}
Application "*" --> "*" Tree : trees
class ApplicationBackground [[java:org.sitmun.plugin.core.domain.ApplicationBackground]] {
}
Application --> "*" ApplicationBackground : backgrounds
class CartographyGroup [[java:org.sitmun.plugin.core.domain.CartographyGroup]] {
}
Application --> "1" CartographyGroup : situationMap
class TaskGroup [[java:org.sitmun.plugin.core.domain.TaskGroup]] {
	-long id
	-String name
	+long getId()
	+void setId(long id)
	+String getName()
	+void setName(String name)
}
class CartographyAvailability [[java:org.sitmun.plugin.core.domain.CartographyAvailability]] {
	-long id
	-Date createdDate
	+long getId()
	+void setId(long id)
	+Date getCreatedDate()
	+void setCreatedDate(Date createdDate)
	+Territory getTerritory()
	+void setTerritory(Territory territory)
	+Cartography getCartography()
	+void setCartography(Cartography cartography)
	+String toString()
}
class Territory [[java:org.sitmun.plugin.core.domain.Territory]] {
}
CartographyAvailability --> "1" Territory : territory
class Cartography [[java:org.sitmun.plugin.core.domain.Cartography]] {
}
CartographyAvailability --> "1" Cartography : cartography
class TaskAvailability [[java:org.sitmun.plugin.core.domain.TaskAvailability]] {
	-long id
	-Date createdDate
	+long getId()
	+void setId(long id)
	+Date getCreatedDate()
	+void setCreatedDate(Date createdDate)
	+Territory getTerritory()
	+void setTerritory(Territory territory)
	+Task getTask()
	+void setTask(Task task)
}
class Territory [[java:org.sitmun.plugin.core.domain.Territory]] {
}
TaskAvailability --> "1" Territory : territory
class Task [[java:org.sitmun.plugin.core.domain.Task]] {
}
TaskAvailability --> "1" Task : task
class Cartography [[java:org.sitmun.plugin.core.domain.Cartography]] {
	-long id
	-String name
	-String type
	-Boolean visible
	-Integer transparency
	-Boolean queryable
	-Boolean queryAct
	-Boolean queryLay
	-Date createdDate
	-Integer order
	-Integer minimumScale
	-Integer maximumScale
	-String layers
	-Boolean selectable
	-String selectionLayer
	-String legendTip
	-String legendUrl
	-Boolean editable
	-String metadataUrl
	-Boolean themeable
	-String geometryType
	+long getId()
	+void setId(long id)
	+String getName()
	+void setName(String name)
	+String getType()
	+void setType(String type)
	+Boolean getVisible()
	+void setVisible(Boolean visible)
	+Integer getTransparency()
	+void setTransparency(Integer transparency)
	+Boolean getQueryable()
	+void setQueryable(Boolean queryable)
	+Boolean getQueryAct()
	+void setQueryAct(Boolean queryAct)
	+Boolean getQueryLay()
	+void setQueryLay(Boolean queryLay)
	+Date getCreatedDate()
	+void setCreatedDate(Date createdDate)
	+Integer getOrder()
	+void setOrder(Integer order)
	+Integer getMinimumScale()
	+void setMinimumScale(Integer minimumScale)
	+Integer getMaximumScale()
	+void setMaximumScale(Integer maximumScale)
	+String getLayers()
	+void setLayers(String layers)
	+Service getService()
	+void setService(Service service)
	+Connection getConnection()
	+void setConnection(Connection connection)
	+Set<CartographyAvailability> getAvailabilities()
	+void setAvailabilities(Set<CartographyAvailability> availabilities)
	+Boolean getSelectable()
	+void setSelectable(Boolean selectable)
	+String getSelectionLayer()
	+void setSelectionLayer(String selectionLayer)
	+Service getSelectionService()
	+void setSelectionService(Service selectionService)
	+String getLegendTip()
	+void setLegendTip(String legendTip)
	+String getLegendUrl()
	+void setLegendUrl(String legendUrl)
	+Boolean getEditable()
	+void setEditable(Boolean editable)
	+String getMetadataUrl()
	+void setMetadataUrl(String metadataUrl)
	+Boolean getThemeable()
	+void setThemeable(Boolean themeable)
	+String getGeometryType()
	+void setGeometryType(String geometryType)
}
class Service [[java:org.sitmun.plugin.core.domain.Service]] {
}
Cartography --> "1" Service : service
class Connection [[java:org.sitmun.plugin.core.domain.Connection]] {
}
Cartography --> "1" Connection : connection
class CartographyAvailability [[java:org.sitmun.plugin.core.domain.CartographyAvailability]] {
}
Cartography --> "*" CartographyAvailability : availabilities
class Service [[java:org.sitmun.plugin.core.domain.Service]] {
}
Cartography --> "1" Service : selectionService
class Tree [[java:org.sitmun.plugin.core.domain.Tree]] {
	-long id
	-String name
	+long getId()
	+void setId(long id)
	+String getName()
	+void setName(String name)
	+Set<TreeNode> getNodes()
	+void setNodes(Set<TreeNode> nodes)
}
class TreeNode [[java:org.sitmun.plugin.core.domain.TreeNode]] {
}
Tree --> "*" TreeNode : nodes
class ServiceParameter [[java:org.sitmun.plugin.core.domain.ServiceParameter]] {
	-long id
	-String name
	-String value
	-String type
	+long getId()
	+void setId(long id)
	+String getName()
	+void setName(String name)
	+String getValue()
	+void setValue(String value)
	+String getType()
	+void setType(String type)
	+Service getService()
	+void setService(Service service)
}
class Service [[java:org.sitmun.plugin.core.domain.Service]] {
}
ServiceParameter --> "1" Service : service
class TaskParameter [[java:org.sitmun.plugin.core.domain.TaskParameter]] {
	-long id
	-String name
	-String value
	-String type
	-Integer order
	+long getId()
	+void setId(long id)
	+String getName()
	+void setName(String name)
	+String getValue()
	+void setValue(String value)
	+String getType()
	+void setType(String type)
	+Task getTask()
	+void setTask(Task task)
	+Integer getOrder()
	+void setOrder(Integer order)
}
class Task [[java:org.sitmun.plugin.core.domain.Task]] {
}
TaskParameter --> "1" Task : task
class ApplicationBackground [[java:org.sitmun.plugin.core.domain.ApplicationBackground]] {
	-long id
	-Integer order
	+long getId()
	+void setId(long id)
	+Integer getOrder()
	+void setOrder(Integer order)
	+Application getApplication()
	+void setApplication(Application application)
	+Background getBackground()
	+void setBackground(Background background)
}
class Application [[java:org.sitmun.app.admin.Application]] {
}
ApplicationBackground --> "1" Application : application
class Background [[java:org.sitmun.plugin.core.domain.Background]] {
}
ApplicationBackground --> "1" Background : background
class Role [[java:org.sitmun.plugin.core.domain.Role]] {
	-long id
	-String name
	-String comments
	+long getId()
	+void setId(long id)
	+String getName()
	+void setName(String name)
	+String getComments()
	+void setComments(String comments)
}
class Territory [[java:org.sitmun.plugin.core.domain.Territory]] {
	-long id
	-String name
	-String email
	-String address
	-String organizationName
	-String scope
	-String logo
	-String ext
	-Boolean blocked
	-String comments
	-Date createdDate
	+long getId()
	+void setId(long id)
	+String getName()
	+void setName(String name)
	+String getEmail()
	+void setEmail(String email)
	+String getAddress()
	+void setAddress(String address)
	+String getOrganizationName()
	+void setOrganizationName(String organizationName)
	+String getScope()
	+void setScope(String scope)
	+String getLogo()
	+void setLogo(String logo)
	+String getExt()
	+void setExt(String ext)
	+Boolean getBlocked()
	+void setBlocked(Boolean blocked)
	+String getComments()
	+void setComments(String comments)
	+Date getCreatedDate()
	+void setCreatedDate(Date createdDate)
	+Set<Territory> getMembers()
	+void setMembers(Set<Territory> members)
	+Set<Territory> getMemberOf()
	+void setMemberOf(Set<Territory> memberOf)
	+TerritoryType getType()
	+void setType(TerritoryType type)
}
class Territory [[java:org.sitmun.plugin.core.domain.Territory]] {
}
Territory --> "*" Territory : members
class Territory [[java:org.sitmun.plugin.core.domain.Territory]] {
}
Territory --> "*" Territory : memberOf
class TerritoryType [[java:org.sitmun.plugin.core.domain.TerritoryType]] {
}
Territory --> "1" TerritoryType : type
class TreeNode [[java:org.sitmun.plugin.core.domain.TreeNode]] {
	-long id
	-String name
	-String tooltip
	-Integer ordee
	-Boolean active
	+long getId()
	+void setId(long id)
	+String getName()
	+void setName(String name)
	+String getTooltip()
	+void setTooltip(String tooltip)
	+Integer getOrdee()
	+void setOrdee(Integer ordee)
	+Boolean getActive()
	+void setActive(Boolean active)
	+TreeNode getParent()
	+void setParent(TreeNode parent)
	+Tree getTree()
	+void setTree(Tree tree)
	+Cartography getCartography()
	+void setCartography(Cartography cartography)
}
class TreeNode [[java:org.sitmun.plugin.core.domain.TreeNode]] {
}
TreeNode --> "1" TreeNode : parent
class Tree [[java:org.sitmun.plugin.core.domain.Tree]] {
}
TreeNode --> "1" Tree : tree
class Cartography [[java:org.sitmun.plugin.core.domain.Cartography]] {
}
TreeNode --> "1" Cartography : cartography
class Log [[java:org.sitmun.plugin.core.domain.Log]] {
	-long id
	-String nombre
	-String codigoUsuario
	-String codigoAplicacion
	-String codigoTerritorio
	-String codigoTarea
	-String contenido
	-Date fecha
	+long getId()
	+void setId(long id)
	+String getNombre()
	+void setNombre(String nombre)
	+String getCodigoUsuario()
	+void setCodigoUsuario(String codigoUsuario)
	+String getCodigoAplicacion()
	+void setCodigoAplicacion(String codigoAplicacion)
	+String getCodigoTerritorio()
	+void setCodigoTerritorio(String codigoTerritorio)
	+String getCodigoTarea()
	+void setCodigoTarea(String codigoTarea)
	+String getContenido()
	+void setContenido(String contenido)
	+Date getFecha()
	+void setFecha(Date fecha)
}
class TaskType [[java:org.sitmun.plugin.core.domain.TaskType]] {
	-long id
	-String name
	+long getId()
	+void setId(long id)
	+String getName()
	+void setName(String name)
}
class Task [[java:org.sitmun.plugin.core.domain.Task]] {
	-long id
	-String name
	-Integer order
	-Date createdDate
	+long getId()
	+void setId(long id)
	+String getName()
	+void setName(String name)
	+Integer getOrder()
	+void setOrder(Integer order)
	+Date getCreatedDate()
	+void setCreatedDate(Date createdDate)
	+Connection getConnection()
	+void setConnection(Connection connection)
	+Set<Role> getRoles()
	+void setRoles(Set<Role> roles)
	+Set<TaskAvailability> getAvailabilities()
	+void setAvailabilities(Set<TaskAvailability> availabilities)
	+TaskGroup getGroup()
	+void setGroup(TaskGroup group)
	+TaskType getType()
	+void setType(TaskType type)
}
class Connection [[java:org.sitmun.plugin.core.domain.Connection]] {
}
Task --> "1" Connection : connection
class Role [[java:org.sitmun.plugin.core.domain.Role]] {
}
Task --> "*" Role : roles
class TaskAvailability [[java:org.sitmun.plugin.core.domain.TaskAvailability]] {
}
Task --> "*" TaskAvailability : availabilities
class TaskGroup [[java:org.sitmun.plugin.core.domain.TaskGroup]] {
}
Task --> "1" TaskGroup : group
class TaskType [[java:org.sitmun.plugin.core.domain.TaskType]] {
}
Task --> "1" TaskType : type
class Connection [[java:org.sitmun.plugin.core.domain.Connection]] {
	-long id
	-String name
	-String type
	-String user
	-String password
	-String connectionString
	+long getId()
	+void setId(long id)
	+String getName()
	+void setName(String name)
	+String getType()
	+void setType(String type)
	+String getUser()
	+void setUser(String user)
	+String getPassword()
	+void setPassword(String password)
	+String getConnectionString()
	+void setConnectionString(String connectionString)
}
class User [[java:org.sitmun.plugin.core.domain.User]] {
	-long id
	-String username
	-String password
	-String firstName
	-String lastName
	-Boolean administrator
	-Boolean blocked
	+long getId()
	+void setId(long id)
	+String getUsername()
	+void setUsername(String username)
	+String getPassword()
	+void setPassword(String password)
	+String getFirstName()
	+void setFirstName(String firstName)
	+String getLastName()
	+void setLastName(String lastName)
	+Boolean getAdministrator()
	+void setAdministrator(Boolean administrator)
	+Boolean getBlocked()
	+void setBlocked(Boolean blocked)
	+Set<UserPosition> getPositions()
	+void setPositions(Set<UserPosition> positions)
	+Set<UserConfiguration> getPermissions()
	+void setPermissions(Set<UserConfiguration> permissions)
}
class UserPosition [[java:org.sitmun.plugin.core.domain.UserPosition]] {
}
User --> "*" UserPosition : positions
class UserConfiguration [[java:org.sitmun.plugin.core.domain.UserConfiguration]] {
}
User --> "*" UserConfiguration : permissions
class ApplicationParameter [[java:org.sitmun.plugin.core.domain.ApplicationParameter]] {
	-long id
	-String name
	-String value
	-String type
	+long getId()
	+void setId(long id)
	+String getName()
	+void setName(String name)
	+String getValue()
	+void setValue(String value)
	+String getType()
	+void setType(String type)
	+Application getApplication()
	+void setApplication(Application application)
}
class Application [[java:org.sitmun.app.admin.Application]] {
}
ApplicationParameter --> "1" Application : application
class UserPosition [[java:org.sitmun.plugin.core.domain.UserPosition]] {
	-long id
	-String name
	-String organization
	-String email
	-Date createdDate
	-Date datedDate
	+long getId()
	+void setId(long id)
	+String getName()
	+void setName(String name)
	+String getOrganization()
	+void setOrganization(String organization)
	+String getEmail()
	+void setEmail(String email)
	+Date getCreatedDate()
	+void setCreatedDate(Date createdDate)
	+Date getDatedDate()
	+void setDatedDate(Date datedDate)
	+User getUser()
	+void setUser(User user)
	+Territory getTerritory()
	+void setTerritory(Territory territory)
}
class User [[java:es.aragon.agoab.domain.User]] {
}
UserPosition --> "1" User : user
class Territory [[java:org.sitmun.plugin.core.domain.Territory]] {
}
UserPosition --> "1" Territory : territory

@enduml