@startuml

skinparam componentStyle uml2

title Dynamic Technology Diagram


node "App" as app {
    rectangle "Client" as client {
        [OpenLayers4] as ol
        [Material Angular] as ma
        [Angular6] as an
    }
    
    rectangle "Server" as server {
        rectangle "Spring5" as spring {
            [REST Controller] as rest
            interface API as api
            [Model] as model
        }
        [Hibernate] as hi
    }
    

} 

database "Database" as db{
}

cloud Internet as internet {
}

:User:


 
User <-down-> internet
internet <-down-> client
client -left-( api
api <-left-> rest
rest -left- model
model -left- hi
hi <-left-> db


@enduml