@startuml
title Build Infraestructure
skinparam linetype ortho


rectangle "Developer Computer" {
    rectangle "Gradle Builds" as gradleconf {
        [Gradlew] as gradlew
        [Java] as jv
        [Sonarqube] as sq
        [Maven] as mv
    }
    rectangle "Angular/Node builds" as nodeconf {
        [Npm] as npm
        [Ng] as ng
        [Sonarqube] as sqn
    }
[Git] as git
}


rectangle "GitHub" {
    rectangle "GitHub Repositories" as github
    rectangle "Github Packages" as ghp
}


rectangle "CI Server" as ci

rectangle "SonarCloud" as sonar



gradlew ..> sq
gradlew ..> mv
gradlew ..> jv



git .right.> "pull / push" github
github .down.> "built on" ci

ci ..> "analyzed on" sonar
gradleconf .down.> "analyzed on" sonar

gradleconf .down.> "published to" ghp
nodeconf .down.> "published to" ghp
ci "published to" .left.> ghp
@enduml
