@startuml

skinparam componentStyle uml2
skinparam linetype ortho

title Main packages and libraries

package "sitmun-admin-app" as admin <<Angular Application>> #Orange

package "sitmun-territorial-app" as territorial <<Angular Application>> #Orange

package "sitmun-plugin-demo" <<Angular Library>> as pd #LightPink

package "@sitmun/frontend-gui" as sfg <<Angular Library>> #LightPink {
}

package "OpenLayers4" as OL4 <<JavaScript>>
package "@angular/material" as MA <<Angular Library>>

sfg ..> OL4
sfg ..> MA


package "@sitmun/frontend-core" <<Angular Library>> as sfc #LightPink


package "Angular" as An <<TypeScript>>


package "org.sitmun.plugin.core" as core <<Java Library>> #LightSkyBlue {
} 

package "Spring" as Spr <<Java>> #LightSteelBlue{
  package "SpringBoot" as SprB <<Java>> #LightSteelBlue
  package "Hibernate" as Hi <<Java>> #LightSteelBlue
}

core ..> Spr


territorial ..> pd
territorial ..> sfg
territorial ..> sfc
territorial ..> core


admin ..> sfg
admin ..> sfc
admin ..> core

pd ..> sfg
pd ..> sfc

sfg ..> An
sfc ..> An

sfg ..> sfc

@enduml
