@startuml

skinparam componentStyle uml2

title Static Technology Diagram

package "sitmun-admin-app" as admin {
    package "App Graphic User\nInterface" as gui1
}

package "sitmun-territorial-app" as territorial {
    package "App Graphic User\nInterface" as gui2
}


package "sitmun-plugin-demo" as demo {

}

package "sitmun-plugin-core" as core {
    package "OpenLayers4" as ol
    package "Material Angular" as ma
    package "Angular6" as an
    package "SpringBoot" as sb
    package "Spring5" as sp
    package "Hibernate" as hi
} 


admin -down..> core
territorial -down..> core
demo ..> core

@enduml
